apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-api
spec:
  template:
    spec:
      containers:
        - name: public-api
          env:
            - name: spring.profiles.active
              value: production