apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: public-api
  name: public-api
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: public-api
  type: ClusterIP
status:
  loadBalancer: {}
